travis:
  secure:
    BINSTAR_TOKEN: KmQCaO1zDDJ8SwoK8REXHE9QLekLY+/qfZxD4Bie/fHUIzZTHy4XUR/9KRELEZRdnuKmfqkyLXviRuHNjZv12638oF9mmKy5v+GlI/eGmvIRe8Qf8cmG319dgIylRnSfheTRsWoqlbme4Huebh0KYH8iJ6bZXpT9wHynNyqru7Fo0t9i/LhLwKNLeGQ9pxr3W3rRfJfVQ3PZSz7zmBwdeIhkNf8+iOa7Lms5480eCvLmpRgl9EjEKP3KZNrncCrw3dck6xami3y6mvEZGfunnreMku9d0B6p7Yef9993wkVTTBg9dmw4IW0k1bUwHii1jrNrlyH4Fjxsfgi/L0FR95W8WHtIC/6yDcxTJZSB7bWQn3uHICRWmYVXXHkKOGeqHrrpiGPI7cYE2yaTXKooV2CEHSGF92acGo3R81URr3FRxWZ6CT7C/FEoelKk1rOPcviusYhhjOWgUvhuSwnO53wsQXtX3MseTXDJxREFLTRkjDsksev5jZQaJPSYaWgGuD7f4wjnriyvK8qKD14EcW00N0HkZezRlAFORNM3T27alSrKlzSu6+TRSUpD136WKgqIoBM97GLuVlLGI3aYqKk9tvFRJyRGcQK21KcANq6o9br2F1OVBWzI1OnD6x2yfpCr05sijxTsL/AYIAg/beRmMtr7N5eM0CrQeqZO6pA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
